### ISSUE TITLE
Token configuration must be the same as APP__ADMIN__TOKEN

### ISSUE THREAD

**Issue by adrianovieira** [OpenCTI-Platform/docker#19]
For a simple try I just copied `.env.sample` to `.env` file.

Steps to reproduce:

1. `cp .env.sample .env`
2. `docker-compose up`

So, this error occours for:

- connector-history
- connector-export-file-stix
- connector-import-file-stix
- connector-import-file-pdf-observables

docker version: 19.03.14 or 20.10.2
docker-compose version: 1.28.0

logging:
<details>

```
Starting docker_minio_1                                 ... done
Starting docker_connector-history_1                     ... done
Starting docker_elasticsearch_1                         ... done
Starting docker_connector-import-file-stix_1            ... done
Starting docker_connector-import-file-pdf-observables_1 ... done
Starting docker_redis_1                                 ... done
Starting docker_connector-export-file-stix_1            ... done
Starting docker_rabbitmq_1                              ... done
Starting docker_connector-export-file-csv_1             ... done
Starting docker_opencti_1                               ... done
Starting docker_worker_1                                ... done
Starting docker_worker_2                                ... done
Starting docker_worker_3                                ... done
Attaching to docker_connector-import-file-pdf-observables_1, docker_connector-import-file-stix_1, docker_connector-history_1, docker_minio_1, docker_elasticsearch_1, docker_redis_1, docker_connector-export-file-csv_1, docker_rabbitmq_1, docker_connector-export-file-stix_1, docker_opencti_1, docker_worker_1, docker_worker_2, docker_worker_3
connector-history_1                      | Traceback (most recent call last):
connector-history_1                      |   File "history.py", line 70, in <module>
connector-history_1                      |     HistoryInstance = HistoryConnector()
connector-history_1                      |   File "history.py", line 20, in __init__
connector-history_1                      |     self.helper = OpenCTIConnectorHelper(config)
connector-history_1                      |   File "/usr/local/lib/python3.8/site-packages/pycti/connector/opencti_connector_helper.py", line 308, in __init__
connector-history_1                      |     self.api = OpenCTIApiClient(
connector-history_1                      |   File "/usr/local/lib/python3.8/site-packages/pycti/api/opencti_api_client.py", line 89, in __init__
connector-history_1                      |     raise ValueError(
connector-history_1                      | ValueError: Token configuration must be the same as APP__ADMIN__TOKEN
minio_1                                  | 
minio_1                                  |  You are running an older version of MinIO released 1 month ago 
minio_1                                  |  Update: Run `mc admin update` 
minio_1                                  | 
minio_1                                  | 
minio_1                                  | Endpoint:  http://172.18.0.5:9000  http://127.0.0.1:9000
minio_1                                  | 
minio_1                                  | Browser Access:
minio_1                                  |    http://172.18.0.5:9000  http://127.0.0.1:9000
minio_1                                  | 
minio_1                                  | Object API (Amazon S3 compatible):
minio_1                                  |    Go:         https://docs.min.io/docs/golang-client-quickstart-guide
minio_1                                  |    Java:       https://docs.min.io/docs/java-client-quickstart-guide
minio_1                                  |    Python:     https://docs.min.io/docs/python-client-quickstart-guide
minio_1                                  |    JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
minio_1                                  |    .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
opencti_1                                | yarn run v1.19.1
opencti_1                                | $ node build/index.js
redis_1                                  | 1:C 22 Jan 2021 17:56:48.939 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1                                  | 1:C 22 Jan 2021 17:56:48.939 # Redis version=6.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1                                  | 1:C 22 Jan 2021 17:56:48.939 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1                                  | 1:M 22 Jan 2021 17:56:48.940 * Running mode=standalone, port=6379.
redis_1                                  | 1:M 22 Jan 2021 17:56:48.940 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1                                  | 1:M 22 Jan 2021 17:56:48.940 # Server initialized
redis_1                                  | 1:M 22 Jan 2021 17:56:48.940 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1                                  | 1:M 22 Jan 2021 17:56:48.940 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo madvise > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled (set to 'madvise' or 'never').
redis_1                                  | 1:M 22 Jan 2021 17:56:48.943 * Loading RDB produced by version 6.0.9
redis_1                                  | 1:M 22 Jan 2021 17:56:48.943 * RDB age 68 seconds
redis_1                                  | 1:M 22 Jan 2021 17:56:48.943 * RDB memory usage when created 0.77 Mb
redis_1                                  | 1:M 22 Jan 2021 17:56:48.943 * DB loaded from disk: 0.000 seconds
redis_1                                  | 1:M 22 Jan 2021 17:56:48.943 * Ready to accept connections
worker_1                                 | Traceback (most recent call last):
worker_1                                 |   File "worker.py", line 281, in <module>
worker_1                                 |     worker = Worker()
worker_1                                 |   File "worker.py", line 208, in __init__
worker_1                                 |     self.opencti_url, self.opencti_token, self.log_level
worker_1                                 |   File "/usr/local/lib/python3.7/site-packages/pycti/api/opencti_api_client.py", line 90, in __init__
worker_1                                 |     "Token configuration must be the same as APP__ADMIN__TOKEN"
worker_1                                 | ValueError: Token configuration must be the same as APP__ADMIN__TOKEN
worker_3                                 | Traceback (most recent call last):
worker_3                                 |   File "worker.py", line 281, in <module>
worker_3                                 |     worker = Worker()
worker_3                                 |   File "worker.py", line 208, in __init__
worker_3                                 |     self.opencti_url, self.opencti_token, self.log_level
worker_3                                 |   File "/usr/local/lib/python3.7/site-packages/pycti/api/opencti_api_client.py", line 90, in __init__
worker_3                                 |     "Token configuration must be the same as APP__ADMIN__TOKEN"
worker_3                                 | ValueError: Token configuration must be the same as APP__ADMIN__TOKEN
worker_2                                 | Traceback (most recent call last):
worker_2                                 |   File "worker.py", line 281, in <module>
worker_2                                 |     worker = Worker()
worker_2                                 |   File "worker.py", line 208, in __init__
worker_2                                 |     self.opencti_url, self.opencti_token, self.log_level
worker_2                                 |   File "/usr/local/lib/python3.7/site-packages/pycti/api/opencti_api_client.py", line 90, in __init__
worker_2                                 |     "Token configuration must be the same as APP__ADMIN__TOKEN"
worker_2                                 | ValueError: Token configuration must be the same as APP__ADMIN__TOKEN
connector-import-file-pdf-observables_1  | Token configuration must be the same as APP__ADMIN__TOKEN
connector-import-file-stix_1             | Token configuration must be the same as APP__ADMIN__TOKEN
docker_connector-history_1 exited with code 1
connector-export-file-csv_1              | Token configuration must be the same as APP__ADMIN__TOKEN
connector-export-file-stix_1             | Token configuration must be the same as APP__ADMIN__TOKEN
opencti_1                                | {"error":{"name":"ConfigurationError","_error":{},"_showLocations":false,"_showPath":false,"time_thrown":"2021-01-22T17:57:02.229Z","data":{"reason":"ElasticSearch seems down","category":"technical"},"internalData":{}},"level":"error","message":"[OPENCTI] Platform initialization fail","timestamp":"2021-01-22T17:57:02.229Z"}
opencti_1                                | error Command failed with exit code 1.
opencti_1                                | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
docker_worker_1 exited with code 1
docker_worker_3 exited with code 1
docker_worker_2 exited with code 1
worker_3                                 | Traceback (most recent call last):
worker_3                                 |   File "worker.py", line 281, in <module>
worker_3                                 |     worker = Worker()
worker_3                                 |   File "worker.py", line 208, in __init__
worker_3                                 |     self.opencti_url, self.opencti_token, self.log_level
worker_3                                 |   File "/usr/local/lib/python3.7/site-packages/pycti/api/opencti_api_client.py", line 90, in __init__
worker_3                                 |     "Token configuration must be the same as APP__ADMIN__TOKEN"
worker_3                                 | ValueError: Token configuration must be the same as APP__ADMIN__TOKEN
worker_1                                 | Traceback (most recent call last):
worker_1                                 |   File "worker.py", line 281, in <module>
worker_1                                 |     worker = Worker()
worker_1                                 |   File "worker.py", line 208, in __init__
worker_1                                 |     self.opencti_url, self.opencti_token, self.log_level
worker_1                                 |   File "/usr/local/lib/python3.7/site-packages/pycti/api/opencti_api_client.py", line 90, in __init__
worker_1                                 |     "Token configuration must be the same as APP__ADMIN__TOKEN"
worker_1                                 | ValueError: Token configuration must be the same as APP__ADMIN__TOKEN
worker_2                                 | Traceback (most recent call last):
worker_2                                 |   File "worker.py", line 281, in <module>
worker_2                                 |     worker = Worker()
worker_2                                 |   File "worker.py", line 208, in __init__
worker_2                                 |     self.opencti_url, self.opencti_token, self.log_level
worker_2                                 |   File "/usr/local/lib/python3.7/site-packages/pycti/api/opencti_api_client.py", line 90, in __init__
worker_2                                 |     "Token configuration must be the same as APP__ADMIN__TOKEN"
worker_2                                 | ValueError: Token configuration must be the same as APP__ADMIN__TOKEN
```
</details>

**Comment by SamuelHassine** [comment]
Hello @adrianovieira,

Please read the documentation about Docker deployment, you cannot just copy the sample. As you can see in the `.env.sample` file, there are some "ChangeMe" value :)

Kind regards,
Samuel

**Comment by adrianovieira** [comment]
I was only trying start it up as a simple test on how it works!

How I could do simply start up it on my laptop?

**Comment by adrianovieira** [comment]
So, lets share a sample `.env` file with values, e.g.:

```
OPENCTI_ADMIN_EMAIL=none@email.io
OPENCTI_ADMIN_PASSWORD=S3cr3t-ChangeMe
OPENCTI_ADMIN_TOKEN=6c031fc8-7330-4d63-b50e-ca4534d0d403
MINIO_ACCESS_KEY=S3cr3t-ChangeMeAccess
MINIO_SECRET_KEY=S3cr3t-ChangeMeKey
RABBITMQ_DEFAULT_USER=guest
RABBITMQ_DEFAULT_PASS=guest
CONNECTOR_HISTORY_ID=269adbe8-19e9-4852-af91-a54ca60e6dea
CONNECTOR_EXPORT_FILE_STIX_ID=ab1ef947-84c2-43d0-9645-6cb78eebfa16
CONNECTOR_EXPORT_FILE_CSV_ID=aaeefccb-cc8f-4f52-a784-e59854a40476
CONNECTOR_IMPORT_FILE_STIX_ID=4096af4e-06f1-4469-9a22-d023560c4c23
CONNECTOR_IMPORT_FILE_PDF_OBSERVABLES_ID=8505075d-e4ab-40e6-bdb4-8358f784d540
```

Although it logs some errors, e.g.:<details>
```
worker_1                                 | INFO:root:Listing Threat-Actors with filters null.
worker_1                                 | Traceback (most recent call last):
worker_1                                 |   File "worker.py", line 281, in <module>
worker_1                                 |     worker = Worker()
worker_1                                 |   File "worker.py", line 208, in __init__
worker_1                                 |     self.opencti_url, self.opencti_token, self.log_level
worker_1                                 |   File "/usr/local/lib/python3.7/site-packages/pycti/api/opencti_api_client.py", line 144, in __init__
worker_1                                 |     "OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration..."
worker_1                                 | ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
worker_1                                 | INFO:root:Listing Threat-Actors with filters null.
worker_1                                 | Traceback (most recent call last):
```
</details>

It starts.

**Comment by Janoruca** [comment]
Look in yout docker-compose.yml for each environment variable
Example:
In your docker-compose.yml in opencti->environment must said APP__ADMIN__EMAIL=${OPENCTI_ADMIN_EMAIL}

**Comment by richard-julien** [comment]
Closed for inactivity

**Comment by adrianovieira** [comment]
> Look in yout docker-compose.yml for each environment variable
> Example:
> In your docker-compose.yml in opencti->environment must said APP__ADMIN__EMAIL=${OPENCTI_ADMIN_EMAIL}

I've been using the docker-compose as same as the one in this repo (e.g.: https://github.com/OpenCTI-Platform/docker/blob/master/docker-compose.yml)
