### ISSUE TITLE
ReplyError: ERR no such key

### ISSUE THREAD

**Issue by mwatermolen** [OpenCTI-Platform/docker#26]
[ERROR]

### Services
**Elastic:**      7.12.1
**rabbitmq:** 3.8-management
**minio:**       RELEASE.2021-04-22T15-44-28Z
**redis:**         6.2.2
**opencti/platform:** 4.5.0

---
**Platform:** Kubernetes

**Issue:** Upon initialization the startup of the opencti container the error below is thrown. 

***I have verified connectivity to redis, minio, rabbitmq, and elastic***

**Error:**
```
Mon, May 10 2021 11:59:09 am | {"category":"APP","version":"4.5.0","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2021-05-10T16:59:09.331Z"}
Mon, May 10 2021 11:59:09 am | {"category":"APP","version":"4.5.0","level":"info","message":"[CHECK] ElasticSearch is alive","timestamp":"2021-05-10T16:59:09.420Z"}
Mon, May 10 2021 11:59:09 am | {"category":"APP","version":"4.5.0","level":"info","message":"[CHECK] Minio is alive","timestamp":"2021-05-10T16:59:09.450Z"}
Mon, May 10 2021 11:59:09 am | {"category":"APP","version":"4.5.0","level":"info","message":"[CHECK] RabbitMQ is alive","timestamp":"2021-05-10T16:59:09.517Z"}
Mon, May 10 2021 11:59:09 am | {"category":"APP","version":"4.5.0","level":"info","message":"[CHECK] Redis is alive","timestamp":"2021-05-10T16:59:09.518Z"}
Mon, May 10 2021 11:59:10 am | {"category":"APP","version":"4.5.0","level":"info","message":"[CHECK] Python3 is available","timestamp":"2021-05-10T16:59:10.530Z"}
Mon, May 10 2021 11:59:10 am | {"category":"APP","version":"4.5.0","level":"info","message":"[INIT] Existing platform detected, initialization...","timestamp":"2021-05-10T16:59:10.569Z"}
Mon, May 10 2021 11:59:11 am | {"category":"APP","version":"4.5.0","level":"info","message":"[INIT] admin user initialized","timestamp":"2021-05-10T16:59:11.672Z"}
Mon, May 10 2021 11:59:11 am | {"category":"APP","version":"4.5.0","level":"info","message":"[MIGRATION] Read 0 migrations from the database","timestamp":"2021-05-10T16:59:11.715Z"}
Mon, May 10 2021 11:59:11 am | {"category":"APP","version":"4.5.0","level":"info","message":"[MIGRATION] Platform already up to date, nothing to migrate","timestamp":"2021-05-10T16:59:11.717Z"}
Mon, May 10 2021 11:59:11 am | {"category":"APP","version":"4.5.0","level":"info","message":"[MIGRATION] Migration process completed","timestamp":"2021-05-10T16:59:11.719Z"}
Mon, May 10 2021 11:59:14 am | {"category":"APP","version":"4.5.0","level":"info","message":"[STREAM] Starting streaming processor","timestamp":"2021-05-10T16:59:14.212Z"}
Mon, May 10 2021 11:59:14 am | {"category":"APP","version":"4.5.0","level":"info","message":"[OPENCTI] Servers ready on port 8080","timestamp":"2021-05-10T16:59:14.217Z"}
Mon, May 10 2021 11:59:14 am | node:internal/process/promises:245
Mon, May 10 2021 11:59:14 am | triggerUncaughtException(err, true /* fromPromise */);
Mon, May 10 2021 11:59:14 am | ^
Mon, May 10 2021 11:59:14 am |  
Mon, May 10 2021 11:59:14 am | ReplyError: ERR no such key
Mon, May 10 2021 11:59:14 am | at se (/opt/opencti/build/index.js:1:87463)
Mon, May 10 2021 11:59:14 am | at i (/opt/opencti/build/index.js:1:87927)
Mon, May 10 2021 11:59:14 am | at /opt/opencti/build/index.js:1:88227
Mon, May 10 2021 11:59:14 am | at Object.start (/opt/opencti/build/index.js:1:88270)
Mon, May 10 2021 11:59:14 am | at processTicksAndRejections (node:internal/process/task_queues:94:5)
Mon, May 10 2021 11:59:14 am | at async Ft (/opt/opencti/build/index.js:1:232051) {
Mon, May 10 2021 11:59:14 am | command: { name: 'XINFO', args: [ 'STREAM', 'stream.opencti' ] }
Mon, May 10 2021 11:59:14 am | }

```
![image](https://user-images.githubusercontent.com/73605619/117696234-aeb89b00-b186-11eb-8d27-67a53197a904.png)

**Comment by mwatermolen** [comment]
Just saw this has yet to be pushed, will test with rolling container and report back

**Comment by SamuelHassine** [comment]
@richard-julien This is related to Redis cluster no?

**Comment by mwatermolen** [comment]
@SamuelHassine Much appreciated! If you don't mind, will you ping this chat or slack when its pushed?

**Comment by mwatermolen** [comment]
@SamuelHassine looks like both issues are now resolved in the latest rolling release
