### ISSUE TITLE
Invalid RabbitMQ Credentials on docker installation

### ISSUE THREAD

**Issue by Arikius** [OpenCTI-Platform/docker#304]
Even after chaning the local .env file and re-composing , i see to be getting the following error on the OPENCTI Docker (main one)

{"category":"APP","errors":[{"attributes":{"genre":"TECHNICAL","http_status":500},"message":"RabbitMQ seems down","name":"DATABASE_ERROR","stack":"DATABASE_ERROR: RabbitMQ seems down\n    at error (/opt/opencti/build/src/config/errors.js:8:10)\n    at DatabaseError (/opt/opencti/build/src/config/errors.js:58:48)\n    at /opt/opencti/build/src/database/rabbitmq.js:242:13\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at checkSystemDependencies (/opt/opencti/build/src/initialization.js:37:3)\n    at platformStart (/opt/opencti/build/src/boot.js:14:7)"},{"message":"Handshake terminated by server: 403 (ACCESS-REFUSED) with message \"ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.\"","name":"Error","stack":"Error: Handshake terminated by server: 403 (ACCESS-REFUSED) with message \"ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.\"\n    at k (/opt/opencti/build/node_modules/amqplib/lib/connection.js:172:16)\n    at cb (/opt/opencti/build/node_modules/amqplib/lib/connection.js:107:11)\n    at Socket.recv (/opt/opencti/build/node_modules/amqplib/lib/connection.js:456:9)\n    at Object.onceWrapper (node:events:633:28)\n    at Socket.emit (node:events:519:28)\n    at emitReadable_ (node:internal/streams/readable:832:12)\n    at processTicksAndRejections (node:internal/process/task_queues:81:21)"}],"level":"error","message":"RabbitMQ seems down","source":"backend","timestamp":"2024-07-19T18:26:12.500Z","version":"6.2.6"}

On the Rabbitmq Node

2024-07-19 18:27:19.405452+00:00 [error] <0.747.0> PLAIN login refused: user 'opencti' - invalid credentials
2024-07-19 18:27:19.406444+00:00 [info] <0.747.0> closing AMQP connection <0.747.0> (172.18.0.10:49734 -> 172.18.0.5:5672)
2024-07-19 18:28:25.869322+00:00 [info] <0.754.0> accepting AMQP connection <0.754.0> (172.18.0.10:45814 -> 172.18.0.5:5672)
2024-07-19 18:28:25.874491+00:00 [error] <0.754.0> Error on AMQP connection <0.754.0> (172.18.0.10:45814 -> 172.18.0.5:5672, state: starting):
2024-07-19 18:28:25.874491+00:00 [error] <0.754.0> PLAIN login refused: user 'opencti' - invalid credentials
2024-07-19 18:28:25.875473+00:00 [info] <0.754.0> closing AMQP connection <0.754.0> (172.18.0.10:45814 -> 172.18.0.5:5672)

**Comment by Arikius** [comment]
Seems it passes this stage if i put guest (both user and pass) in Rabbit MQ Env
