### ISSUE TITLE
Add wait-for-it to reduce errors at the startup

### ISSUE THREAD

**Issue by 2xyo** [OpenCTI-Platform/docker#6]
In order to reduce error logs at the startup of the `docker-compose up`, could you add a wrapper script such as `wait-for-it`: ``` command: ["./wait-for-it.sh", "opencti:8080", "--", "/entrypoint.sh"] ```

Documentation: https://docs.docker.com/compose/startup-order/
 
Sample of the error just because the API is not up at the startup:
```onnector-mitre_1             | INFO:root:Listing Threat-Actors with filters null.
connector-mitre_1             | Traceback (most recent call last):
connector-mitre_1             |   File "mitre.py", line 88, in <module>
connector-mitre_1             |     mitreConnector = Mitre()
connector-mitre_1             |   File "mitre.py", line 15, in __init__
connector-mitre_1             |     self.helper = OpenCTIConnectorHelper(config)
connector-mitre_1             |   File "/usr/local/lib/python3.7/site-packages/pycti/connector/opencti_connector_helper.py", line 150, in __init__
connector-mitre_1             |     self.api = OpenCTIApiClient(self.opencti_url, self.opencti_token, self.log_level)
connector-mitre_1             |   File "/usr/local/lib/python3.7/site-packages/pycti/api/opencti_api_client.py", line 106, in __init__
connector-mitre_1             |     raise ValueError('OpenCTI API seems down')
connector-mitre_1             | ValueError: OpenCTI API seems down
````

**Comment by HugoPouliquen** [comment]
👍

**Comment by SamuelHassine** [comment]
We reduced the log footprint in the next release.
