### ISSUE TITLE
Could not load credentials from any providers

### ISSUE THREAD

**Issue by mccramer** [OpenCTI-Platform/docker#72]
Need help to figure out how I can solve this. I have deployed the server in Azure Cloud, used docker-compose.yml and stack deploy.

{"category":"APP","level":"info","message":"[OPENCTI] Starting platform","timestamp":"2023-01-18T02:29:10.979Z","version":"5.5.2"}
{"category":"APP","level":"info","message":"[OPENCTI] Checking dependencies statuses","timestamp":"2023-01-18T02:29:10.982Z","version":"5.5.2"}
{"category":"APP","level":"info","message":"[SEARCH] Elasticsearch (8.5.3) client selected / runtime sorting enabled","timestamp":"2023-01-18T02:29:11.047Z","version":"5.5.2"}
{"category":"APP","level":"info","message":"[CHECK] Search engine is alive","timestamp":"2023-01-18T02:29:11.049Z","version":"5.5.2"}
{"category":"APP","error":{"context":{},"message":"Could not load credentials from any providers","name":"CredentialsProviderError","stack":"CredentialsProviderError: Could not load credentials from any providers\n    at provider (/opt/opencti/build/src/database/file-storage.js:45:13)\n    at /opt/opencti/build/node_modules/@aws-sdk/property-provider/dist-cjs/chain.js:11:28\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at coalesceProvider (/opt/opencti/build/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:14:24)\n    at _Be.credentialProvider (/opt/opencti/build/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:33:24)\n    at _Be.signRequest (/opt/opencti/build/node_modules/@aws-sdk/signature-v4/dist-cjs/SignatureV4.js:86:29)\n    at /opt/opencti/build/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:16:18\n    at /opt/opencti/build/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46\n    at /opt/opencti/build/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:5:22\n    at initializeBucket (/opt/opencti/build/src/database/file-storage.js:76:5)\n    at checkSystemDependencies (/opt/opencti/build/src/initialization.js:132:3)\n    at boot (/opt/opencti/build/src/boot.js:10:5)"},"level":"error","message":"[OPENCTI] Platform start fail","timestamp":"2023-01-18T02:29:11.088Z","version":"5.5.2"}

version: '3'
#networks:
#    ext0:
#        external: true

services:
  redis:
    container_name: opencti-redis
    image: redis:7.0.6
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redisdata:/data:rw 
  elasticsearch:
    container_name: opencti-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    volumes:
      - esdata:/usr/share/elasticsearch/data:rw
    ports:
      - 9200:9200/tcp
      - 9300:9300/tcp
    environment:
      #- bootstrap.memory_lock=true
      #- http.cors.enabled=true
      #- http.cors.allow-origin=*
     # - ELASTICSEARCH_SSL_CA=/home/ansible/.opencti-ssl/opencti-play.pem
      # Comment out the line below for single-node
      - discovery.type=single-node
      # Uncomment line below below for a cluster of multiple nodes
      # - cluster.name=docker-cluster
      - xpack.ml.enabled=false
      - xpack.security.enabled=false
      #- "ES_JAVA_OPTS=-Xms${ELASTIC_MEMORY_SIZE} -Xmx${ELASTIC_MEMORY_SIZE}"
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  opencti-kibana:
    container_name: opencti-kibana
    image: docker.elastic.co/kibana/kibana:8.5.3
    environment:
      - ELASTICSEARCH_HOSTS=http://opencti-elasticsearch:9200
    restart: always
    ports:
      - 5601:5601
    depends_on: 
      - opencti-elasticsearch
  minio:
    container_name: opencti-minio
    image: minio/minio:RELEASE.2022-09-25T15-44-53Z
    volumes:
      - s3data:/data:rw
    ports:
      - 9001:9001/tcp
      - 9000:9000/tcp
      - 127.0.0.1:50001:9000/tcp
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}    
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
  rabbitmq:
    container_name: opencti-rabbitmq
    image: rabbitmq:3.11-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - amqpdata:/var/lib/rabbitmq:rw
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
  opencti:
    container_name: opencti-platform
    image: opencti/platform:5.5.2
    environment:
      - NODE_OPTIONS=--max-old-space-size=8096
      - APP__PORT=8080
      - APP__BASE_URL=${OPENCTI_BASE_URL}
    #  - APP__REACTIVE=true
      - APP__ADMIN__EMAIL=${OPENCTI_ADMIN_EMAIL}
      - APP__ADMIN__PASSWORD=${OPENCTI_ADMIN_PASSWORD}
      - APP__ADMIN__TOKEN=${OPENCTI_ADMIN_TOKEN}
      - APP__APP_LOGS__LOGS_LEVEL=debug
    #  - APP__LOGS=/var/log/opencti
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__URL=http://opencti-elasticsearch:9200
    #  - ELASTICSEARCH_SSL_CA=/home/ansible/.opencti-ssl/opencti-play.pem
      - MINIO__ENDPOINT=minio
      - MINIO__PORT=9001
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO__SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - SMTP__HOSTNAME=${SMTP_HOSTNAME}
      - SMTP__PORT=25
      - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
    #  - APP__HTTPS_CERT__CA='["${SSL_ROOT_CA}"]'
    volumes:
      - ${SSL_ROOT_CA}:/etc/ssl/certs/opencti.crt:ro
    networks:
        default:
    ports:
      - 8080:8080/tcp
      - 127.0.0.1:50000:8080/tcp
    labels:
      - "ext0.enable=true"
      - "ext0.http.routers.opencti.rule=Host(`${DOCKER_IP}`)"
      - "ext0.http.routers.opencti.entrypoints=https"
      - "ext0.http.services.opencti.loadbalancer.server.port=8080"
    depends_on:
      - redis
      - elasticsearch
      - minio
      - rabbitmq
    restart: always
    deploy:
      placement:
        constraints:
          - "node.role==manager"
  worker:
    image: opencti/worker:5.5.2
    environment:
      - OPENCTI_URL=http://127.0.0.1:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - WORKER_LOG_LEVEL=info
    depends_on:
      - opencti
    deploy:
      mode: replicated
      replicas: 3
    restart: always
  connector-export-file-stix:
    image: opencti/connector-export-file-stix:5.5.2
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_STIX_ID}
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileStix2
      - CONNECTOR_SCOPE=application/json
      - CONNECTOR_CONFIDENCE_LEVEL=3 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
    restart: always
    depends_on:
      - opencti
  connector-export-file-csv:
    image: opencti/connector-export-file-csv:5.5.2
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_CSV_ID}
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileCsv
      - CONNECTOR_SCOPE=text/csv
      - CONNECTOR_CONFIDENCE_LEVEL=3 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
    restart: always
    depends_on:
      - opencti
  connector-export-file-txt:
    image: opencti/connector-export-file-txt:5.5.2
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_FILE_TXT_ID}
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileTxt
      - CONNECTOR_SCOPE=text/plain
      - CONNECTOR_CONFIDENCE_LEVEL=3 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
    restart: always
    depends_on:
      - opencti
  connector-import-file-stix:
    image: opencti/connector-import-file-stix:5.5.2
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_IMPORT_FILE_STIX_ID}
      - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
      - CONNECTOR_NAME=ImportFileStix
      - CONNECTOR_VALIDATE_BEFORE_IMPORT=true
      - CONNECTOR_SCOPE=application/json,text/xml
      - CONNECTOR_AUTO=true
      - CONNECTOR_CONFIDENCE_LEVEL=3 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
    restart: always
    depends_on:
      - opencti
  #connector-import-file-pdf-observables:
  #  environment:
  #    - CONNECTOR_CONFIDENCE_LEVEL=3
  #    - CONNECTOR_ID=${CONNECTOR_IMPORT_FILE_PDF_ID}
  #    - CONNECTOR_LOG_LEVEL=info
  #    - CONNECTOR_NAME=ImportFilePdfObservables
  #    - CONNECTOR_SCOPE=application/pdf
  #    - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
  #    - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
  #    - OPENCTI_URL=http://opencti:8080
  #    - PDF_OBSERVABLES_CREATE_INDICATOR=False
  #  image: opencti/connector-import-file-pdf-observables:5.5.2
  #  restart: always
  #  depends_on:
  #    - opencti
  connector-import-document:
    image: opencti/connector-import-document:5.5.2
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_IMPORT_DOCUMENT_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
      - CONNECTOR_NAME=ImportDocument
      - CONNECTOR_VALIDATE_BEFORE_IMPORT=true # Validate any bundle before import
      - CONNECTOR_SCOPE=application/pdf,text/plain,text/html
      - CONNECTOR_AUTO=true # Enable/disable auto-import of file
      - CONNECTOR_ONLY_CONTEXTUAL=false # Only extract data related to an entity (a report, a threat actor, etc.)
      - CONNECTOR_CONFIDENCE_LEVEL=3 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
      - IMPORT_DOCUMENT_CREATE_INDICATOR=true
    restart: always
    depends_on:
      - opencti

volumes:
  esdata:
  s3data:
  redisdata:
  amqpdata:
#  ssldata:

**Comment by tern001** [comment]
Everything else looks fine in the logs except the "Could not load credentials from any provider". I have no idea how to pass that ^^

**Comment by jfrpo1-iscte** [comment]
I have a similar issue :(
