### ISSUE TITLE
push_sync queue not found in rabbitmq

### ISSUE THREAD

**Issue by 0q1627** [OpenCTI-Platform/docker#80]
A.K.A. "Error An unknown error occurred. Please contact your administrator or the OpenCTI maintainers." on Connectors.

SUMMARY.
Keeping ES data (it's on a dedicated host), when all connectors are reset to the initial state, OpenCTI complains that rabbitmq is Disconnected. Instead OpenCTI and rabbitmq do communicate but the "push_sync" queue is not recreated.

Hello.
I'm running latest 5.6.2 docker-compose. I've been setting up OpenCTI like this:
- opencti and associated containers on a host except for
- ES on a separate host

This setup required few trial and errors, fights with docker when changin stuff in the .yml (my inexperience), and several containers resets. Except for ES.

I am now stuck with OpenCTI saying that rabbitmq is Disconnected, which blocks me from handling connectors over the web interface (and I think they don't sync, either).

I can log into rabbitmq via the admin interface, see OpenCTI creating queues for the configured uuid's, so they DO communicate.

In rabbitmq log there is a recurrent error about push_sync queue missing:
```
## THE ERROR
2023-03-14 08:24:07.725336+00:00 [error] <0.4851.0> Channel error on connection <0.4842.0> (172.25.0.1:44582 -> 172.25.0.8:5672, vhost: '/', user: 'guest'), channel 1:
2023-03-14 08:24:07.725336+00:00 [error] <0.4851.0> operation basic.consume caused a channel exception not_found: no queue 'push_sync' in vhost '/'
## THE OTHER TRAFFIC
2023-03-14 08:24:24.370621+00:00 [info] <0.4866.0> accepting AMQP connection <0.4866.0> (172.25.0.1:47862 -> 172.25.0.8:5672)
2023-03-14 08:24:24.374583+00:00 [info] <0.4869.0> accepting AMQP connection <0.4869.0> (172.25.0.1:47874 -> 172.25.0.8:5672)
2023-03-14 08:24:24.382954+00:00 [info] <0.4866.0> connection <0.4866.0> (172.25.0.1:47862 -> 172.25.0.8:5672): user 'guest' authenticated and granted access to vhost '/'
2023-03-14 08:24:24.389570+00:00 [info] <0.4869.0> connection <0.4869.0> (172.25.0.1:47874 -> 172.25.0.8:5672): user 'guest' authenticated and granted access to vhost '/'
2023-03-14 08:24:24.415833+00:00 [info] <0.4866.0> closing AMQP connection <0.4866.0> (172.25.0.1:47862 -> 172.25.0.8:5672, vhost: '/', user: 'guest')
2023-03-14 08:24:24.417784+00:00 [info] <0.4901.0> accepting AMQP connection <0.4901.0> (172.25.0.1:47890 -> 172.25.0.8:5672)
```

And OpenCTI log when I click on "Connectors":

```
{"category":"APP","error":{"stacktrace":["AxiosError:` Request failed with status code 403","at settle (/opt/opencti/build/node_modules/axios/lib/core/settle.js:19:12)","at IncomingMessage.handleStreamEnd (/opt/opencti/build/node_modules/axios/lib/adapters/http.js:556:11)","at IncomingMessage.emit (node:events:525:35)","at endReadableNT (node:internal/streams/readable:1359:12)","at processTicksAndRejections (node:internal/process/task_queues:82:21)"]},"inner_relation_creation":0,"level":"error","message":"API Call","operation":"ConnectorsStatusQuery","operation_query":"query ConnectorsStatusQuery{...ConnectorsStatus_data}fragment ConnectorsStatus_data on Query{connectors{id name active auto connector_type connector_scope updated_at config{listen listen_exchange push push_exchange}}rabbitMQMetrics{queues{name messages messages_ready messages_unacknowledged consumers idle_since message_stats{ack ack_details{rate}}}}}","size":2,"time":21,"timestamp":"2023-03-14T08:36:55.726Z","type":"READ_ERROR","user":{"ip":"::ffff:1.x.y.z","referer":"http://10.10.10.2:8080/dashboard/data/connectors","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"variables":{},"version":"5.6.2"}

{"category":"APP","error":{"stacktrace":["AxiosError: Request failed with status code 403","at settle (/opt/opencti/build/node_modules/axios/lib/core/settle.js:19:12)","at IncomingMessage.handleStreamEnd (/opt/opencti/build/node_modules/axios/lib/adapters/http.js:556:11)","at IncomingMessage.emit (node:events:525:35)","at endReadableNT (node:internal/streams/readable:1359:12)","at processTicksAndRejections (node:internal/process/task_queues:82:21)"]},"inner_relation_creation":0,"level":"error","message":"API Call","operation":"WorkersStatusQuery","operation_query":"query WorkersStatusQuery{...WorkersStatus_data}fragment WorkersStatus_data on Query{elasticSearchMetrics{docs{count}search{query_total fetch_total}indexing{index_total delete_total}get{total}}rabbitMQMetrics{consumers overview{queue_totals{messages messages_ready messages_unacknowledged}message_stats{ack ack_details{rate}}}}}","size":2,"time":37,"timestamp":"2023-03-14T08:36:55.734Z","type":"READ_ERROR","user":{"ip":"::ffff:1.x.y.z","referer":"http://10.10.10.2:8080/dashboard/data/connectors","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"variables":{},"version":"5.6.2"}

```

It has worked because I've started adding connectors and importing data. Then at a reset of containers it broke. I've reset containers several times except for ElasticSearch data, that has been unaltered. I restarted opencti connector alone but it doesn't seem to recreate the required push_sync queue.

What's the way out, please?

**Comment by 0q1627** [comment]
It was the proxy. If your docker host needs a proxy to connect to the Internet, and so do your connectors, make sure it is configured only for those containers that do need it.

The main opencti container doesn't need the proxy. Make sure that it has no proxy-related environment variable with the command

`docker exec [opencti_container_runtime_name] env`
